### model
model_name_or_path: /root/.cache/modelscope/hub/ydyajyA/Llama-2-13b-chat-hf/
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all 
### ddp
ddp_timeout: 180000000
deepspeed: deepspeed/ds_z0_config.json

### dataset
dataset: hf_train
cutoff_len: 8192
template: llama2
packing: true
neat_packing: true
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama2-13b/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
include_effective_tokens_per_second: true
include_tokens_per_second: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 3.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
disable_gradient_checkpointing: false
warmup_ratio: 0.1
bf16: true

